# CUDA-образ: ultralytics official image с CUDA 12.4
# syntax=docker/dockerfile:1
FROM ultralytics/ultralytics:8.3.135

WORKDIR /app

COPY src ./src
COPY data.yaml /app/data.yaml

ENV PYTHONUNBUFFERED=1

CMD ["python", "src/train.py"]
