# Параметры для Liquibase внутри контейнера app-db (localhost)
changelog-file=changelog/db.changelog-master.yaml
search-path=/liquibase/workspace
url=jdbc:postgresql://127.0.0.1:5432/app-mis
username=postgres
password=postgres
driver=org.postgresql.Driver
