# Ручной запуск: docker run ... --network mis_default (хост app-db)
changelog-file=changelog/db.changelog-master.yaml
search-path=.
url=jdbc:postgresql://app-db:5432/app-mis
username=postgres
password=postgres
driver=org.postgresql.Driver
