# Локальный запуск (app-db на хосте :5435)
changelog-file=changelog/db.changelog-master.yaml
search-path=.
url=jdbc:postgresql://localhost:5435/app-mis
username=postgres
password=postgres
driver=org.postgresql.Driver
