version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres-app-db
    env_file:
      - ./s.app-db.env
    ports:
      - "5434:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app_db_data: