services:
  keycloak-db:
    image: postgres:18-alpine
    container_name: keycloak-db
    env_file:
      - ./s.kc-db-conf.env
    ports:
      - "5433:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    ports:
      - "8081:8080"
    env_file:
      - ./s.kc-conf.env
    depends_on:
      keycloak-db:
          condition: service_healthy
    restart: unless-stopped

  app-db:
    image: postgres:18-alpine
    container_name: app-db
    ports:
      - "5435:5432"
    volumes:
      - app_db_data:/var/lib/postgresql
    env_file:
      - s.app-db-conf.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura-db:
    image: postgres:18-alpine
    container_name: hasura-db
    ports:
      - "5434:5432"
    volumes:
      - hasura_db_data:/var/lib/postgresql
    env_file:
      - s.hasura-conf.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura-graphql-engine:
    image: hasura/graphql-engine:v2.48.13.cli-migrations-v3
    container_name: hasura-graphql-engine
    ports:
      - "8080:8080"
    env_file:
      - s.hasura-conf.env
    depends_on:
      hasura-data-connector-agent:
        condition: service_healthy
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata

  hasura-data-connector-agent:
    image: hasura/graphql-data-connector:v2.48.13
    container_name: hasura-data-connector-agent
    restart: always
    ports:
      - 8081:8081
    env_file:
      - s.app-db-conf.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/athena/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  keycloak_db_data:
  app_db_data:
  hasura_db_data:
