# CUDA-образ: PyTorch с поддержкой GPU
# syntax=docker/dockerfile:1
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

WORKDIR /app

COPY requirements-gpu.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

ENV PYTHONUNBUFFERED=1
WORKDIR /app/src

CMD ["python", "train.py"]
